context:
  version: "0.15.1"

package:
  name: millet
  version: ${{ version }}

source:
  url: https://github.com/azdavis/millet/archive/v${{ version }}.tar.gz
  sha256: ba5651ab14a07b2f2f09aad11f151e0fe4e767ccc4064122a5c56308c0320244

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - millet-cli --help

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE.md
    - LICENSE-MIT.md
    - THIRDPARTY.yml
  summary: A language server for Standard ML in Rust.
  homepage: https://github.com/azdavis/millet
  repository: https://github.com/azdavis/millet

extra:
  recipe-maintainers:
    - danielnachun
