context:
  version: "0.15.2"

package:
  name: millet
  version: ${{ version }}

source:
  url: https://github.com/azdavis/millet/archive/v${{ version }}.tar.gz
  sha256: dd0de00174182013543efe91e4755e56611fe872f40d5b9f1353b7a319d7f711

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - millet-cli --help

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE.md
    - LICENSE-MIT.md
    - THIRDPARTY.yml
  summary: A language server for Standard ML in Rust.
  homepage: https://github.com/azdavis/millet
  repository: https://github.com/azdavis/millet

extra:
  recipe-maintainers:
    - danielnachun
