context:
  version: "0.14.9"

package:
  name: millet
  version: ${{ version }}

source:
  url: https://github.com/azdavis/millet/archive/v${{ version }}.tar.gz
  sha256: 5efff3cafade17b33a8b9b2748a8c064dbd51932934de01f8d2a14c88ac829c5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - millet-cli --help

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE.md
    - LICENSE-MIT.md
    - THIRDPARTY.yml
  summary: A language server for Standard ML in Rust.
  homepage: https://github.com/azdavis/millet
  repository: https://github.com/azdavis/millet

extra:
  recipe-maintainers:
    - danielnachun
